"use client";

import { useMemo, useState, useEffect } from "react";
import { CheckCircle2, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { WA_PUBLISH, buildWAUrl } from "@/config/whatsapp";
import { saveCart } from "@/app/actions";

function Text({ en, ta }: { en: string; ta: string }) {
  return (
    <>
      <span className="en">{en}</span>
      <span className="ta tamil-text">{ta}</span>
    </>
  );
}

const benefits = [
  ["Reach more rental customers", "அதிக வாடகை வாடிக்கையாளர்களை அடையுங்கள்"],
  ["Earn from idle carts", "பயன்படாத வண்டிகள் மூலம் வருமானம் ஈட்டுங்கள்"],
  ["Get listed in a premium marketplace", "பிரீமியம் சந்தையில் உங்கள் வண்டியை பதிவு செய்யுங்கள்"],
  ["Agree platform fee before listing", "பதிவு செய்வதற்கு முன் கட்டணத்தை ஒப்புக்கொள்ளுங்கள்"]
];

export default function PublishPage() {
  const [lang, setLang] = useState<"en" | "ta">("en");

  // Sync language toggle dynamically
  useEffect(() => {
    if (typeof window === "undefined") return;
    const currentLang = document.documentElement.dataset.lang === "ta" ? "ta" : "en";
    setLang(currentLang);

    const observer = new MutationObserver(() => {
      const updatedLang = document.documentElement.dataset.lang === "ta" ? "ta" : "en";
      setLang(updatedLang);
    });

    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["data-lang"],
    });

    return () => observer.disconnect();
  }, []);

  // Publish Form State
  const [publishFormData, setPublishFormData] = useState({
    name: "",
    phone: "",
    cartType: "Tea", // Tea, Juice, FastFood, Snacks, Empty, Other
    condition: "excellent", // new, excellent, good, fair
    expectedRent: "",
    location: "",
    details: "",
  });

  const [phoneError, setPhoneError] = useState("");

  const handlePublishInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { id, value } = e.target;
    setPublishFormData((prev) => ({ ...prev, [id]: value }));

    if (id === "phone") {
      const digits = value.replace(/\D/g, "");
      if (value && digits.length !== 10) {
        setPhoneError(
          lang === "ta"
            ? "தொலைபேசி எண் 10 இலக்கங்களாக இருக்க வேண்டும்"
            : "Phone number must be exactly 10 digits"
        );
      } else {
        setPhoneError("");
      }
    }
  };

  const isPublishFormValid =
    publishFormData.name.trim() !== "" &&
    publishFormData.phone.replace(/\D/g, "").length === 10 &&
    publishFormData.location.trim() !== "" &&
    publishFormData.expectedRent.trim() !== "" &&
    phoneError === "";

  // This message goes to 7305514199, which must ALWAYS be in English
  const publishCompiledMessage = useMemo(() => {
    const extraDetails = publishFormData.details.trim() !== "" ? publishFormData.details.trim() : "None";
    
    const cartTypeText = 
      publishFormData.cartType === "Tea" ? "Tea / Coffee Cart" :
      publishFormData.cartType === "Juice" ? "Juice / Milkshake Cart" :
      publishFormData.cartType === "FastFood" ? "Fast Food / Chinese Stall" :
      publishFormData.cartType === "Snacks" ? "Snacks / Chaat Cart" :
      publishFormData.cartType === "Empty" ? "Empty / General Cart" : "Other Cart Variant";
      
    const conditionText =
      publishFormData.condition === "new" ? "Brand New" :
      publishFormData.condition === "excellent" ? "Excellent (Under 1 year)" :
      publishFormData.condition === "good" ? "Good (1-2 years old)" : "Fair (2+ years old)";

    return `Hello Thalluvandi team,

I want to list/publish my cart for rent:

Name: ${publishFormData.name.trim()}
Phone: ${publishFormData.phone.trim()}
Cart Type: ${cartTypeText}
Cart Condition: ${conditionText}
Expected Monthly Rent: ₹${publishFormData.expectedRent.trim()}
Location: ${publishFormData.location.trim()}
Equipment & Description: ${extraDetails}`;
  }, [publishFormData]);

  const handlePublishSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!isPublishFormValid) return;
    
    try {
      await saveCart({
        nameEn: publishFormData.cartType,
        nameTa: publishFormData.cartType,
        type: publishFormData.cartType,
        pricePerDay: Number(publishFormData.expectedRent) || 0,
        depositAmount: 0,
        availableCount: 1,
        descriptionEn: publishFormData.details,
        descriptionTa: publishFormData.details,
      });
    } catch (err) {
      console.error("Failed to save cart to backend:", err);
    }

    const waUrl = buildWAUrl(WA_PUBLISH, publishCompiledMessage);
    window.open(waUrl, "_blank");
  };

  return (
    <main className="bg-[#F8F6F2] pt-16 md:pt-28">
      {/* Dynamic SEO Meta Tags are generated by metadata config in layout/page metadata */}
      <section className="pb-20 pt-24 md:pb-24 md:pt-0">
        <div className="site-container grid gap-12 md:grid-cols-[1fr_1.1fr] md:gap-12 items-start">
          <div className="flex flex-col justify-between h-full py-4">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">
                <Text en="Vendor Network" ta="வண்டி உரிமையாளர் நெட்வொர்க்" />
              </p>
              <h1 className="mt-3 font-display text-5xl uppercase leading-none text-ink md:text-7xl">
                <Text en="List Your Thallu Vandi Across Tamil Nadu" ta="தமிழ்நாடு முழுவதும் உங்கள் வண்டியை பதிவு செய்யுங்கள்" />
              </h1>
              <p className="mt-6 max-w-[680px] text-lg leading-8 text-muted">
                <Text 
                  en="If you own a food cart and want more rental customers, publish it on Thalluvandi. We list verified carts on our premium platform for local vendors to hire daily!" 
                  ta="உங்களுக்கு தள்ளுவண்டி இருந்தால் தள்ளுவண்டி தளத்தில் உங்கள் வண்டியை பதிவு செய்யுங்கள் — உங்கள் பகுதிக்கேற்ப வாடிக்கையாளர்களை நாங்கள் பெற்றுத் தருகிறோம்!" 
                />
              </p>
            </div>
            
            <div className="mt-10 border-t border-black/5 pt-8">
              <h3 className="font-bold text-sm uppercase tracking-wider text-primary mb-4">
                <Text en="Need Quick Info?" ta="விரைவான தகவல் தேவையா?" />
              </h3>
              <p className="text-sm leading-relaxed text-muted max-w-md">
                <Text 
                  en="Filling the listing form on the right compiles a structured email/message instantly to our list coordinator on WhatsApp. We will verify your cart specifications and list it within 24 hours." 
                  ta="வலதுபுறம் உள்ள படிவத்தை நிரப்பினால், உங்கள் வண்டி வாடகைக்கு விடப்படும் விவரங்கள் உடனடியாக எங்கள் ஒருங்கிணைப்பாளருக்கு வாட்ஸ்அப்பில் அனுப்பப்படும். 24 மணி நேரத்திற்குள் சரிபார்க்கப்பட்டு பதிவு செய்யப்படும்." 
                />
              </p>
            </div>
          </div>

          <div className="rounded-2xl border border-black/10 bg-[#fffdf7] p-6 shadow-premium md:p-8 flex flex-col gap-5">
            <div>
              <h2 className="font-display text-4xl uppercase leading-none text-ink">
                <Text en="Publish & List Cart" ta="வண்டி வாடகைக்கு விட" />
              </h2>
              <p className="mt-1 text-xs text-[#f97316] font-bold uppercase tracking-wider">
                <Text en="Interactive WhatsApp Listing" ta="நேரடி வாட்ஸ்அப் பதிவேற்றம்" />
              </p>
            </div>

            <form onSubmit={handlePublishSubmit} className="space-y-4">
              
              {/* Field 1: Name */}
              <div className="flex flex-col">
                <label htmlFor="name" className="text-sm font-semibold mb-1 block">
                  <Text en="Full Name *" ta="பெயர் *" />
                </label>
                <input
                  type="text"
                  id="name"
                  required
                  value={publishFormData.name}
                  onChange={handlePublishInputChange}
                  placeholder={lang === "ta" ? "உங்கள் முழு பெயர்" : "Enter your full name"}
                  className="w-full h-12 border border-[#e5e0d8] focus:border-[#f97316] focus:ring-2 focus:ring-[#f97316]/40 rounded-xl px-4 bg-white text-base outline-none transition"
                />
              </div>

              {/* Field 2: Phone */}
              <div className="flex flex-col">
                <label htmlFor="phone" className="text-sm font-semibold mb-1 block">
                  <Text en="Phone Number *" ta="கைபேசி எண் *" />
                </label>
                <input
                  type="tel"
                  id="phone"
                  required
                  value={publishFormData.phone}
                  onChange={handlePublishInputChange}
                  placeholder={lang === "ta" ? "கைபேசி எண் (10 இலக்கங்கள்)" : "Enter your mobile number"}
                  className={`w-full h-12 border focus:ring-2 rounded-xl px-4 bg-white text-base outline-none transition ${
                    phoneError
                      ? "border-red-500 focus:border-red-500 focus:ring-red-500/40"
                      : "border-[#e5e0d8] focus:border-[#f97316] focus:ring-[#f97316]/40"
                  }`}
                />
                {phoneError && (
                  <span className="text-xs text-red-500 mt-1 font-semibold">
                    {phoneError}
                  </span>
                )}
              </div>

              {/* Field 3: Cart Type Dropdown */}
              <div className="flex flex-col">
                <label htmlFor="cartType" className="text-sm font-semibold mb-1 block">
                  <Text en="Cart Type / Variant *" ta="வண்டி வகை *" />
                </label>
                <select
                  id="cartType"
                  value={publishFormData.cartType}
                  onChange={handlePublishInputChange}
                  className="w-full h-12 border border-[#e5e0d8] focus:border-[#f97316] focus:ring-2 focus:ring-[#f97316]/40 rounded-xl px-4 bg-white text-sm outline-none transition cursor-pointer"
                >
                  {lang === "ta" ? (
                    <>
                      <option value="Tea">டீ / காபி வண்டி</option>
                      <option value="Juice">ஜூஸ் / மில்க்ஷேக் வண்டி</option>
                      <option value="FastFood">ஃபாஸ்ட் ஃபுட் வண்டி</option>
                      <option value="Snacks">ஸ்நாக்ஸ் / சாட் வண்டி</option>
                      <option value="Empty">பொதுவான / காலி வண்டி</option>
                      <option value="Other">இதர வண்டி வகை</option>
                    </>
                  ) : (
                    <>
                      <option value="Tea">Tea / Coffee Cart</option>
                      <option value="Juice">Juice / Milkshake Cart</option>
                      <option value="FastFood">Fast Food / Chinese Stall</option>
                      <option value="Snacks">Snacks / Chaat Cart</option>
                      <option value="Empty">Empty / General Cart</option>
                      <option value="Other">Other Cart Variant</option>
                    </>
                  )}
                </select>
              </div>

              {/* Field 4: Cart Condition Dropdown */}
              <div className="flex flex-col">
                <label htmlFor="condition" className="text-sm font-semibold mb-1 block">
                  <Text en="Cart Condition *" ta="வண்டியின் நிலை *" />
                </label>
                <select
                  id="condition"
                  value={publishFormData.condition}
                  onChange={handlePublishInputChange}
                  className="w-full h-12 border border-[#e5e0d8] focus:border-[#f97316] focus:ring-2 focus:ring-[#f97316]/40 rounded-xl px-4 bg-white text-sm outline-none transition cursor-pointer"
                >
                  {lang === "ta" ? (
                    <>
                      <option value="new">புதிய வண்டி</option>
                      <option value="excellent">மிக நன்று (1 வருடத்திற்குள்)</option>
                      <option value="good">நன்று (1-2 வருடங்கள்)</option>
                      <option value="fair">பயன்படுத்தப்பட்டது (2 வருடங்களுக்கு மேல்)</option>
                    </>
                  ) : (
                    <>
                      <option value="new">Brand New</option>
                      <option value="excellent">Excellent (Under 1 year)</option>
                      <option value="good">Good (1-2 years old)</option>
                      <option value="fair">Fair (2+ years old)</option>
                    </>
                  )}
                </select>
              </div>

              {/* Field 5: Expected Rent */}
              <div className="flex flex-col">
                <label htmlFor="expectedRent" className="text-sm font-semibold mb-1 block">
                  <Text en="Expected Monthly Rent (₹) *" ta="எதிர்பார்க்கும் மாத வாடகை (₹) *" />
                </label>
                <input
                  type="number"
                  id="expectedRent"
                  required
                  value={publishFormData.expectedRent}
                  onChange={handlePublishInputChange}
                  placeholder={lang === "ta" ? "எ.கா: 3000" : "e.g. 3000"}
                  className="w-full h-12 border border-[#e5e0d8] focus:border-[#f97316] focus:ring-2 focus:ring-[#f97316]/40 rounded-xl px-4 bg-white text-base outline-none transition"
                />
              </div>

              {/* Field 6: Location (just Location) */}
              <div className="flex flex-col">
                <label htmlFor="location" className="text-sm font-semibold mb-1 block">
                  <Text en="Location *" ta="இடம் *" />
                </label>
                <input
                  type="text"
                  id="location"
                  required
                  value={publishFormData.location}
                  onChange={handlePublishInputChange}
                  placeholder={lang === "ta" ? "எ.கா: ஒண்டிப்புதூர், காந்திபுரம்" : "e.g. Ondipudur, Gandhipuram"}
                  className="w-full h-12 border border-[#e5e0d8] focus:border-[#f97316] focus:ring-2 focus:ring-[#f97316]/40 rounded-xl px-4 bg-white text-base outline-none transition"
                />
              </div>

              {/* Field 7: Equipment / details */}
              <div className="flex flex-col">
                <label htmlFor="details" className="text-sm font-semibold mb-1 block">
                  <Text en="Equipment Included / Details (Optional)" ta="வண்டியில் உள்ள உபகரணங்கள் மற்றும் விவரங்கள் (விருப்பம்)" />
                </label>
                <textarea
                  id="details"
                  rows={4}
                  value={publishFormData.details}
                  onChange={handlePublishInputChange}
                  placeholder={lang === "ta" ? "வண்டியின் அளவு, அடுப்பு, அலமாரி அல்லது பிற வசதிகள்..." : "Cart size, stove type, shelves, or other features..."}
                  className="w-full border border-[#e5e0d8] focus:border-[#f97316] focus:ring-2 focus:ring-[#f97316]/40 rounded-xl p-4 bg-white text-base outline-none transition resize-none"
                />
              </div>

              {/* Submit button */}
              <Button
                type="submit"
                disabled={!isPublishFormValid}
                className={`w-full h-14 mt-4 bg-[#25D366] hover:bg-[#20ba5a] text-white rounded-2xl font-bold text-base flex items-center justify-center gap-2 transition duration-200 ${
                  !isPublishFormValid ? "opacity-40 cursor-not-allowed" : ""
                }`}
              >
                <MessageCircle size={20} className="shrink-0" />
                <Text en="Submit Publish Request (WhatsApp) →" ta="பதிவேற்ற கோரிக்கையை அனுப்பவும் (WhatsApp) →" />
              </Button>

            </form>
          </div>
        </div>
      </section>

      <section className="pb-24">
        <div className="site-container">
          <div className="rounded-2xl border border-black/10 bg-white p-6 md:p-8">
            <h2 className="font-display text-5xl uppercase leading-none text-ink">
              <Text en="Why publish?" ta="ஏன் பதிவு செய்ய வேண்டும்?" />
            </h2>
            <div className="mt-8 grid gap-4 md:grid-cols-2 md:gap-6">
              {benefits.map(([benefit, tamil]) => (
                <div key={benefit} className="flex min-h-14 items-center gap-3 rounded-xl border border-black/10 bg-[#F8F6F2] p-4 text-left font-bold text-ink">
                  <CheckCircle2 className="shrink-0 text-primary" />
                  <Text en={benefit} ta={tamil} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="pb-24">
        <div className="site-container max-w-4xl">
          <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary text-center">
            <Text en="FAQ" ta="கேள்வி பதில்" />
          </p>
          <h2 className="mt-3 font-display text-4xl uppercase leading-none text-ink text-center md:text-5xl">
            <Text en="Publishing Carts FAQ" ta="வண்டிகள் பதிவு கேள்வி பதில்" />
          </h2>

          <div className="mt-12 space-y-4">
            {publishFaqs.map(([question, tamilQuestion, answer, tamilAnswer]) => (
              <details
                key={question}
                className="group rounded-2xl border border-black/10 bg-white p-6 [&_summary::-webkit-details-marker]:hidden"
              >
                <summary className="flex cursor-pointer items-center justify-between gap-1.5 text-ink font-bold">
                  <h3 className="font-display text-xl uppercase tracking-wide leading-tight">
                    <Text en={question} ta={tamilQuestion} />
                  </h3>
                  <span className="shrink-0 rounded-full bg-orange-50 border border-orange-200/50 p-1.5 text-primary group-open:-rotate-180 transition duration-300">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-4 w-4"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth="3"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </span>
                </summary>
                <p className="mt-3 text-[0.95rem] leading-7 text-muted border-t border-black/5 pt-3">
                  <Text en={answer} ta={tamilAnswer} />
                </p>
              </details>
            ))}
          </div>
        </div>
      </section>
      {/* Visually minimal but crawlable SEO text section */}
      <section className="py-6 border-t border-black/5">
        <div className="site-container">
          <p className="text-xs text-muted-foreground text-center max-w-4xl mx-auto leading-relaxed">
            Namma Thalluvandi accepts thallu vandi listings from all Tamil Nadu districts. List your food cart in Chennai, Madurai, Salem, Trichy, Tiruppur, Coimbatore, Erode, Vellore, Tirunelveli, Dindigul, Karur, Namakkal, Dharmapuri, Krishnagiri, Cuddalore, Villupuram, Thanjavur, Kumbakonam, Nagapattinam, Ramanathapuram, Virudhunagar and all other districts. வண்டி பதிவு தமிழ்நாடு முழுவதும்.
          </p>
        </div>
      </section>
    </main>
  );
}

const publishFaqs = [
  [
    "How can I publish my cart on Thalluvandi?",
    "என் வண்டியை தள்ளுவண்டி தளத்தில் எப்படி சேர்ப்பது?",
    "Simply fill out the interactive 'Publish & List Cart' form on this page to instantly contact our network team on WhatsApp. Share your name, phone, location, expected rent, and cart type. Verification and listing are completed in 24 hours.",
    "இப்பக்கத்திலுள்ள 'வண்டி வாடகைக்கு விட' படிவத்தை நிரப்பினால் வாட்ஸ்அப் மூலம் உடனடியாக எங்கள் குழுவினரைத் தொடர்பு கொள்ளலாம். உங்கள் பெயர், போன், இடம், எதிர்பார்க்கும் வாடகை விலை மற்றும் வண்டி வகையை அனுப்புங்கள். 24 மணி நேரத்திற்குள் பதிவு செய்யப்படும்.",
  ],
  [
    "What is the commission/platform fee?",
    "தள்ளுவண்டி தளத்தின் கமிஷன் / சேவை கட்டணம் எவ்வளவு?",
    "Listing your cart is completely free. We only charge a small platform fee or commission when a customer successfully books your cart through our marketplace. The exact fee is discussed and agreed upon before listing.",
    "வண்டியைப் பதிவு செய்வது முற்றிலும் இலவசம். உங்கள் வண்டியை வாடிக்கையாளர்கள் எங்கள் தளம் வழியாக புக் செய்யும் போது மட்டுமே ஒரு சிறிய சேவை கட்டணம் (Platform fee) வசூலிக்கப்படும். இதன் விவரங்களை முன்பே பேசி உறுதி செய்துகொள்ளலாம்.",
  ],
  [
    "Who handles the delivery and return of published carts?",
    "வண்டியை டெலிவரி செய்வதும் திரும்பப் பெறுவதும் யார் பொறுப்பு?",
    "Logistics and transport are typically handled by the renter. However, as the vendor/owner, you must ensure the cart is in a clean, fully functional condition at your specified location for pickup.",
    "போக்குவரத்து மற்றும் டெலிவரி பொதுவாக வாடகைக்கு எடுக்கும் நபரின் பொறுப்பாகும். ஆனால் வண்டி நல்ல முறையில் இயங்கும் நிலையிலும், சுத்தமாகவும் இருப்பதை வண்டியின் உரிமையாளரான நீங்கள் உறுதி செய்ய வேண்டும்.",
  ],
  [
    "How do I get paid for rentals?",
    "என் வண்டிக்கான வாடகை எனக்கு எப்படி கிடைக்கும்?",
    "Rental payouts are transferred directly to you via UPI or Cash weekly, or as per the custom payout frequency we establish with you upon listing.",
    "வண்டிக்கான வாடகை வாராந்திர அடிப்படையில் UPI அல்லது ரொக்கமாக (Cash) நேரடியாக உங்களிடம் ஒப்படைக்கப்படும். அல்லது பதிவு செய்யும் போது பேசப்படும் ஒப்பந்தத்தின்படி வழங்கப்படும்.",
  ],
];
